"""Add English and Ewe suggestion fields to feedback

Revision ID: 3ff3ea17ee8e
Revises: fb6a44ae9055
Create Date: 2025-08-11 20:31:24.268705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff3ea17ee8e'
down_revision = 'fb6a44ae9055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_suggestion_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('term_suggestion_ewe', sa.String(length=200), nullable=True))
        batch_op.drop_column('term_suggestion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_suggestion', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('term_suggestion_ewe')
        batch_op.drop_column('term_suggestion_en')

    # ### end Alembic commands ###
