"""Add term_suggestion_en and term_suggestion_ewe to Feedback

Revision ID: 4f4803b01b24
Revises: 
Create Date: 2025-08-11 17:35:29.103820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4803b01b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_suggestion_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('term_suggestion_ewe', sa.String(length=200), nullable=True))
        batch_op.drop_column('term_suggestion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_suggestion', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('term_suggestion_ewe')
        batch_op.drop_column('term_suggestion_en')

    # ### end Alembic commands ###
