"""Add term_suggestion to feedback

Revision ID: fb6a44ae9055
Revises: 4f4803b01b24
Create Date: 2025-08-11 20:00:06.717627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6a44ae9055'
down_revision = '4f4803b01b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_suggestion', sa.String(length=200), nullable=True))
        batch_op.drop_column('term_suggestion_ewe')
        batch_op.drop_column('term_suggestion_en')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_suggestion_en', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('term_suggestion_ewe', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('term_suggestion')

    # ### end Alembic commands ###
